FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y \
    maven \
    git \
    curl \
    wget \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

# Adicionar jenkins ao grupo docker
RUN groupmod -g 999 docker || groupadd -g 999 docker
RUN usermod -aG docker jenkins

USER jenkins